on:
  workflow_call:
    inputs:
      registry:
        description: 'Docker registry'
        required: false
        type: string
      image-name:
        description: 'Docker image name'
        required: false
        type: string
      username:
        description: 'Username for Docker registry'
        required: false
        type: string
      password:
        description: 'Password for Docker registry'
        required: false
        type: string
      platforms:
        description: 'Platforms to build for'
        required: false
        type: string

name: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
      - uses: azohra/shell-linter@v0.4.0
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: reitermarkus/.github/actions/docker-build-push@main
        with:
          registry: ${{ inputs.registry }}
          image-name: ${{ inputs.image-name }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password || github.token }}
          platforms: ${{ inputs.platforms }}
        id: build-push
